version: '3.7'
services:
  minio:
    image: minio/minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    hostname: minio
    entrypoint: sh
    command: -c 'mkdir -p /data/storage && /usr/bin/minio server /data'  
    networks: 
      ml_platform: {}
  spark-master:
    image: datadrone/spark-master:3.1.1-hadoop3.2-rapids
    ports:
      - "9080:8080"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "PYSPARK_PYTHON=/usr/bin/python3"
      - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"
    networks: 
      ml_platform: {}
  spark-worker-1:
    image: datadrone/spark-worker:3.1.1-hadoop3.2-rapids
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=16
      - SPARK_WORKER_MEMORY=32G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
      - SPARK_WORKER_OPTS=-Dspark.worker.resource.gpu.amount=2 -Dspark.worker.resource.gpu.discoveryScript=/opt/sparkRapidsPlugin/getGpusResources.sh
      - "PYSPARK_PYTHON=/usr/bin/python3"
      - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1']
            capabilities: [gpu, utility, compute]
    networks:
      ml_platform: {}
  spark-notebook:
    image: datadrone/spark_notebook:3.1.1-hadoop3.2
    ports:
      - "9494:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JAVA_HOME=/usr
      - SPARK_MASTER=spark://spark-master:7077
      - "PYSPARK_PYTHON=/usr/bin/python3"
      - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"
    ipc: host  
    networks:
      ml_platform: {}
networks:
  ml_platform:
    external: false
    name: ml_platform